"""Constants for use across the board"""

# Constants
# Required configuration
JOB_PROJECT_ID = 'JOB_PROJECT_ID'
JOB_NAME = 'JOB_NAME'
JOB_ZONE = 'JOB_ZONE'
WORKER_COUNT = 'WORKER_COUNT'
MAX_WORKER_COUNT = 'MAX_WORKER_COUNT'
WORKER_TYPE = 'WORKER_TYPE'
STREAM_MODE = 'STREAM_MODE'
AUTOSCALING_TYPE = 'AUTOSCALING_TYPE'
LOG_LEVEL = 'LOG_LEVEL'
STAGING_STORAGE_BUCKET = 'STAGING_STORAGE_BUCKET'
RUNNER = 'RUNNER'

# Pubsub configuration
PUBSUB_WRITE = 'PUBSUB_WRITE'
PUBSUB_READ = 'PUBSUB_READ'
PUBSUB_READ_VERBATIM = 'PUBSUB_READ_VERBATIM'

# Pom configuration
POM = 'POM'
JAR_NAME_FORMAT = 'JAR_NAME_FORMAT'

# Flow configuration
FLOW = 'PARAMS'
