"""Constants for use across the board"""

# Constants
JOB_PROJECT_ID = 'JOB_PROJECT_ID'
JOB_NAME = 'JOB_NAME'
JOB_ZONE = 'JOB_ZONE'
WORKER_COUNT = 'WORKER_COUNT'
MAX_WORKER_COUNT = 'MAX_WORKER_COUNT'
WORKER_TYPE = 'WORKER_TYPE'
STREAM_MODE = 'STREAM_MODE'
AUTOSCALING_TYPE = 'AUTOSCALING_TYPE'
PUBSUB_WRITE = 'PUBSUB_WRITE'
PUBSUB_READ = 'PUBSUB_READ'
PUBSUB_READ_VERBATIM = 'PUBSUB_READ_VERBATIM'
FLOW = 'PARAMS'
POM = 'POM'
LOG_LEVEL = 'LOG_LEVEL'
STAGING_STORAGE_BUCKET = 'STAGING_STORAGE_BUCKET'
